# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quinn/Desktop/bz_opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quinn/Desktop/bz_opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Desktop/bz_opengl/CMakeFiles /home/quinn/Desktop/bz_opengl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Desktop/bz_opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named enet_static

# Build rule for target.
enet_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_static
.PHONY : enet_static

# fast build rule for target.
enet_static/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_static.dir/build.make libs/enet/CMakeFiles/enet_static.dir/build
.PHONY : enet_static/fast

#=============================================================================
# Target rules for targets named enet_test

# Build rule for target.
enet_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_test
.PHONY : enet_test

# fast build rule for target.
enet_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_test.dir/build.make libs/enet/CMakeFiles/enet_test.dir/build
.PHONY : enet_test/fast

#=============================================================================
# Target rules for targets named enet_test_extra_peers

# Build rule for target.
enet_test_extra_peers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_test_extra_peers
.PHONY : enet_test_extra_peers

# fast build rule for target.
enet_test_extra_peers/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_test_extra_peers.dir/build.make libs/enet/CMakeFiles/enet_test_extra_peers.dir/build
.PHONY : enet_test_extra_peers/fast

#=============================================================================
# Target rules for targets named enet_test_unit

# Build rule for target.
enet_test_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_test_unit
.PHONY : enet_test_unit

# fast build rule for target.
enet_test_unit/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_test_unit.dir/build.make libs/enet/CMakeFiles/enet_test_unit.dir/build
.PHONY : enet_test_unit/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f libs/spdlog/CMakeFiles/spdlog.dir/build.make libs/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f libs/glm/glm/CMakeFiles/glm.dir/build.make libs/glm/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named threepp

# Build rule for target.
threepp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 threepp
.PHONY : threepp

# fast build rule for target.
threepp/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/src/CMakeFiles/threepp.dir/build.make libs/threepp/src/CMakeFiles/threepp.dir/build
.PHONY : threepp/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/src/external/glfw/src/CMakeFiles/glfw.dir/build.make libs/threepp/src/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/src/external/glfw/src/CMakeFiles/update_mappings.dir/build.make libs/threepp/src/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/client/client.o: src/client/client.cpp.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/client/input.o: src/client/input.cpp.o
.PHONY : src/client/input.o

# target to build an object file
src/client/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/input.cpp.o
.PHONY : src/client/input.cpp.o

src/client/input.i: src/client/input.cpp.i
.PHONY : src/client/input.i

# target to preprocess a source file
src/client/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/input.cpp.i
.PHONY : src/client/input.cpp.i

src/client/input.s: src/client/input.cpp.s
.PHONY : src/client/input.s

# target to generate assembly for a file
src/client/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/input.cpp.s
.PHONY : src/client/input.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/networker.o: src/client/networker.cpp.o
.PHONY : src/client/networker.o

# target to build an object file
src/client/networker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/networker.cpp.o
.PHONY : src/client/networker.cpp.o

src/client/networker.i: src/client/networker.cpp.i
.PHONY : src/client/networker.i

# target to preprocess a source file
src/client/networker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/networker.cpp.i
.PHONY : src/client/networker.cpp.i

src/client/networker.s: src/client/networker.cpp.s
.PHONY : src/client/networker.s

# target to generate assembly for a file
src/client/networker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/networker.cpp.s
.PHONY : src/client/networker.cpp.s

src/client/player.o: src/client/player.cpp.o
.PHONY : src/client/player.o

# target to build an object file
src/client/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.o
.PHONY : src/client/player.cpp.o

src/client/player.i: src/client/player.cpp.i
.PHONY : src/client/player.i

# target to preprocess a source file
src/client/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.i
.PHONY : src/client/player.cpp.i

src/client/player.s: src/client/player.cpp.s
.PHONY : src/client/player.s

# target to generate assembly for a file
src/client/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.s
.PHONY : src/client/player.cpp.s

src/client/renderer.o: src/client/renderer.cpp.o
.PHONY : src/client/renderer.o

# target to build an object file
src/client/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/renderer.cpp.o
.PHONY : src/client/renderer.cpp.o

src/client/renderer.i: src/client/renderer.cpp.i
.PHONY : src/client/renderer.i

# target to preprocess a source file
src/client/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/renderer.cpp.i
.PHONY : src/client/renderer.cpp.i

src/client/renderer.s: src/client/renderer.cpp.s
.PHONY : src/client/renderer.s

# target to generate assembly for a file
src/client/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/renderer.cpp.s
.PHONY : src/client/renderer.cpp.s

src/client/shot.o: src/client/shot.cpp.o
.PHONY : src/client/shot.o

# target to build an object file
src/client/shot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/shot.cpp.o
.PHONY : src/client/shot.cpp.o

src/client/shot.i: src/client/shot.cpp.i
.PHONY : src/client/shot.i

# target to preprocess a source file
src/client/shot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/shot.cpp.i
.PHONY : src/client/shot.cpp.i

src/client/shot.s: src/client/shot.cpp.s
.PHONY : src/client/shot.s

# target to generate assembly for a file
src/client/shot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/shot.cpp.s
.PHONY : src/client/shot.cpp.s

src/server/client.o: src/server/client.cpp.o
.PHONY : src/server/client.o

# target to build an object file
src/server/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client.cpp.o
.PHONY : src/server/client.cpp.o

src/server/client.i: src/server/client.cpp.i
.PHONY : src/server/client.i

# target to preprocess a source file
src/server/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client.cpp.i
.PHONY : src/server/client.cpp.i

src/server/client.s: src/server/client.cpp.s
.PHONY : src/server/client.s

# target to generate assembly for a file
src/server/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client.cpp.s
.PHONY : src/server/client.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/server/networker.o: src/server/networker.cpp.o
.PHONY : src/server/networker.o

# target to build an object file
src/server/networker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/networker.cpp.o
.PHONY : src/server/networker.cpp.o

src/server/networker.i: src/server/networker.cpp.i
.PHONY : src/server/networker.i

# target to preprocess a source file
src/server/networker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/networker.cpp.i
.PHONY : src/server/networker.cpp.i

src/server/networker.s: src/server/networker.cpp.s
.PHONY : src/server/networker.s

# target to generate assembly for a file
src/server/networker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/networker.cpp.s
.PHONY : src/server/networker.cpp.s

src/server/shot.o: src/server/shot.cpp.o
.PHONY : src/server/shot.o

# target to build an object file
src/server/shot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/shot.cpp.o
.PHONY : src/server/shot.cpp.o

src/server/shot.i: src/server/shot.cpp.i
.PHONY : src/server/shot.i

# target to preprocess a source file
src/server/shot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/shot.cpp.i
.PHONY : src/server/shot.cpp.i

src/server/shot.s: src/server/shot.cpp.s
.PHONY : src/server/shot.s

# target to generate assembly for a file
src/server/shot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/shot.cpp.s
.PHONY : src/server/shot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... client"
	@echo "... enet_static"
	@echo "... enet_test"
	@echo "... enet_test_extra_peers"
	@echo "... enet_test_unit"
	@echo "... glfw"
	@echo "... glm"
	@echo "... server"
	@echo "... spdlog"
	@echo "... threepp"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/client/input.o"
	@echo "... src/client/input.i"
	@echo "... src/client/input.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/networker.o"
	@echo "... src/client/networker.i"
	@echo "... src/client/networker.s"
	@echo "... src/client/player.o"
	@echo "... src/client/player.i"
	@echo "... src/client/player.s"
	@echo "... src/client/renderer.o"
	@echo "... src/client/renderer.i"
	@echo "... src/client/renderer.s"
	@echo "... src/client/shot.o"
	@echo "... src/client/shot.i"
	@echo "... src/client/shot.s"
	@echo "... src/server/client.o"
	@echo "... src/server/client.i"
	@echo "... src/server/client.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/networker.o"
	@echo "... src/server/networker.i"
	@echo "... src/server/networker.s"
	@echo "... src/server/shot.o"
	@echo "... src/server/shot.i"
	@echo "... src/server/shot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

