# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quinn/Desktop/bz_opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quinn/Desktop/bz_opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Desktop/bz_opengl/CMakeFiles /home/quinn/Desktop/bz_opengl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Desktop/bz_opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

libs/include/imgui/backends/imgui_impl_glfw.o: libs/include/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : libs/include/imgui/backends/imgui_impl_glfw.o

# target to build an object file
libs/include/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : libs/include/imgui/backends/imgui_impl_glfw.cpp.o

libs/include/imgui/backends/imgui_impl_glfw.i: libs/include/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/include/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
libs/include/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/include/imgui/backends/imgui_impl_glfw.cpp.i

libs/include/imgui/backends/imgui_impl_glfw.s: libs/include/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/include/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
libs/include/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/include/imgui/backends/imgui_impl_glfw.cpp.s

libs/include/imgui/backends/imgui_impl_opengl3.o: libs/include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : libs/include/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
libs/include/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : libs/include/imgui/backends/imgui_impl_opengl3.cpp.o

libs/include/imgui/backends/imgui_impl_opengl3.i: libs/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : libs/include/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
libs/include/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : libs/include/imgui/backends/imgui_impl_opengl3.cpp.i

libs/include/imgui/backends/imgui_impl_opengl3.s: libs/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : libs/include/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
libs/include/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : libs/include/imgui/backends/imgui_impl_opengl3.cpp.s

libs/include/imgui/imgui.o: libs/include/imgui/imgui.cpp.o
.PHONY : libs/include/imgui/imgui.o

# target to build an object file
libs/include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui.cpp.o
.PHONY : libs/include/imgui/imgui.cpp.o

libs/include/imgui/imgui.i: libs/include/imgui/imgui.cpp.i
.PHONY : libs/include/imgui/imgui.i

# target to preprocess a source file
libs/include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui.cpp.i
.PHONY : libs/include/imgui/imgui.cpp.i

libs/include/imgui/imgui.s: libs/include/imgui/imgui.cpp.s
.PHONY : libs/include/imgui/imgui.s

# target to generate assembly for a file
libs/include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui.cpp.s
.PHONY : libs/include/imgui/imgui.cpp.s

libs/include/imgui/imgui_draw.o: libs/include/imgui/imgui_draw.cpp.o
.PHONY : libs/include/imgui/imgui_draw.o

# target to build an object file
libs/include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_draw.cpp.o
.PHONY : libs/include/imgui/imgui_draw.cpp.o

libs/include/imgui/imgui_draw.i: libs/include/imgui/imgui_draw.cpp.i
.PHONY : libs/include/imgui/imgui_draw.i

# target to preprocess a source file
libs/include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_draw.cpp.i
.PHONY : libs/include/imgui/imgui_draw.cpp.i

libs/include/imgui/imgui_draw.s: libs/include/imgui/imgui_draw.cpp.s
.PHONY : libs/include/imgui/imgui_draw.s

# target to generate assembly for a file
libs/include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_draw.cpp.s
.PHONY : libs/include/imgui/imgui_draw.cpp.s

libs/include/imgui/imgui_tables.o: libs/include/imgui/imgui_tables.cpp.o
.PHONY : libs/include/imgui/imgui_tables.o

# target to build an object file
libs/include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_tables.cpp.o
.PHONY : libs/include/imgui/imgui_tables.cpp.o

libs/include/imgui/imgui_tables.i: libs/include/imgui/imgui_tables.cpp.i
.PHONY : libs/include/imgui/imgui_tables.i

# target to preprocess a source file
libs/include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_tables.cpp.i
.PHONY : libs/include/imgui/imgui_tables.cpp.i

libs/include/imgui/imgui_tables.s: libs/include/imgui/imgui_tables.cpp.s
.PHONY : libs/include/imgui/imgui_tables.s

# target to generate assembly for a file
libs/include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_tables.cpp.s
.PHONY : libs/include/imgui/imgui_tables.cpp.s

libs/include/imgui/imgui_widgets.o: libs/include/imgui/imgui_widgets.cpp.o
.PHONY : libs/include/imgui/imgui_widgets.o

# target to build an object file
libs/include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_widgets.cpp.o
.PHONY : libs/include/imgui/imgui_widgets.cpp.o

libs/include/imgui/imgui_widgets.i: libs/include/imgui/imgui_widgets.cpp.i
.PHONY : libs/include/imgui/imgui_widgets.i

# target to preprocess a source file
libs/include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_widgets.cpp.i
.PHONY : libs/include/imgui/imgui_widgets.cpp.i

libs/include/imgui/imgui_widgets.s: libs/include/imgui/imgui_widgets.cpp.s
.PHONY : libs/include/imgui/imgui_widgets.s

# target to generate assembly for a file
libs/include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/libs/include/imgui/imgui_widgets.cpp.s
.PHONY : libs/include/imgui/imgui_widgets.cpp.s

src/client/game.o: src/client/game.cpp.o
.PHONY : src/client/game.o

# target to build an object file
src/client/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/game.cpp.o
.PHONY : src/client/game.cpp.o

src/client/game.i: src/client/game.cpp.i
.PHONY : src/client/game.i

# target to preprocess a source file
src/client/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/game.cpp.i
.PHONY : src/client/game.cpp.i

src/client/game.s: src/client/game.cpp.s
.PHONY : src/client/game.s

# target to generate assembly for a file
src/client/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/game.cpp.s
.PHONY : src/client/game.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/player.o: src/client/player.cpp.o
.PHONY : src/client/player.o

# target to build an object file
src/client/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.o
.PHONY : src/client/player.cpp.o

src/client/player.i: src/client/player.cpp.i
.PHONY : src/client/player.i

# target to preprocess a source file
src/client/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.i
.PHONY : src/client/player.cpp.i

src/client/player.s: src/client/player.cpp.s
.PHONY : src/client/player.s

# target to generate assembly for a file
src/client/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.s
.PHONY : src/client/player.cpp.s

src/client/world.o: src/client/world.cpp.o
.PHONY : src/client/world.o

# target to build an object file
src/client/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/world.cpp.o
.PHONY : src/client/world.cpp.o

src/client/world.i: src/client/world.cpp.i
.PHONY : src/client/world.i

# target to preprocess a source file
src/client/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/world.cpp.i
.PHONY : src/client/world.cpp.i

src/client/world.s: src/client/world.cpp.s
.PHONY : src/client/world.s

# target to generate assembly for a file
src/client/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/world.cpp.s
.PHONY : src/client/world.cpp.s

src/engine/client_engine.o: src/engine/client_engine.cpp.o
.PHONY : src/engine/client_engine.o

# target to build an object file
src/engine/client_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/client_engine.cpp.o
.PHONY : src/engine/client_engine.cpp.o

src/engine/client_engine.i: src/engine/client_engine.cpp.i
.PHONY : src/engine/client_engine.i

# target to preprocess a source file
src/engine/client_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/client_engine.cpp.i
.PHONY : src/engine/client_engine.cpp.i

src/engine/client_engine.s: src/engine/client_engine.cpp.s
.PHONY : src/engine/client_engine.s

# target to generate assembly for a file
src/engine/client_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/client_engine.cpp.s
.PHONY : src/engine/client_engine.cpp.s

src/engine/components/client_network.o: src/engine/components/client_network.cpp.o
.PHONY : src/engine/components/client_network.o

# target to build an object file
src/engine/components/client_network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/client_network.cpp.o
.PHONY : src/engine/components/client_network.cpp.o

src/engine/components/client_network.i: src/engine/components/client_network.cpp.i
.PHONY : src/engine/components/client_network.i

# target to preprocess a source file
src/engine/components/client_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/client_network.cpp.i
.PHONY : src/engine/components/client_network.cpp.i

src/engine/components/client_network.s: src/engine/components/client_network.cpp.s
.PHONY : src/engine/components/client_network.s

# target to generate assembly for a file
src/engine/components/client_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/client_network.cpp.s
.PHONY : src/engine/components/client_network.cpp.s

src/engine/components/gui.o: src/engine/components/gui.cpp.o
.PHONY : src/engine/components/gui.o

# target to build an object file
src/engine/components/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/gui.cpp.o
.PHONY : src/engine/components/gui.cpp.o

src/engine/components/gui.i: src/engine/components/gui.cpp.i
.PHONY : src/engine/components/gui.i

# target to preprocess a source file
src/engine/components/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/gui.cpp.i
.PHONY : src/engine/components/gui.cpp.i

src/engine/components/gui.s: src/engine/components/gui.cpp.s
.PHONY : src/engine/components/gui.s

# target to generate assembly for a file
src/engine/components/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/gui.cpp.s
.PHONY : src/engine/components/gui.cpp.s

src/engine/components/input.o: src/engine/components/input.cpp.o
.PHONY : src/engine/components/input.o

# target to build an object file
src/engine/components/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/input.cpp.o
.PHONY : src/engine/components/input.cpp.o

src/engine/components/input.i: src/engine/components/input.cpp.i
.PHONY : src/engine/components/input.i

# target to preprocess a source file
src/engine/components/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/input.cpp.i
.PHONY : src/engine/components/input.cpp.i

src/engine/components/input.s: src/engine/components/input.cpp.s
.PHONY : src/engine/components/input.s

# target to generate assembly for a file
src/engine/components/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/input.cpp.s
.PHONY : src/engine/components/input.cpp.s

src/engine/components/physics.o: src/engine/components/physics.cpp.o
.PHONY : src/engine/components/physics.o

# target to build an object file
src/engine/components/physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/physics.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/components/physics.cpp.o
.PHONY : src/engine/components/physics.cpp.o

src/engine/components/physics.i: src/engine/components/physics.cpp.i
.PHONY : src/engine/components/physics.i

# target to preprocess a source file
src/engine/components/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/physics.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/components/physics.cpp.i
.PHONY : src/engine/components/physics.cpp.i

src/engine/components/physics.s: src/engine/components/physics.cpp.s
.PHONY : src/engine/components/physics.s

# target to generate assembly for a file
src/engine/components/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/physics.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/components/physics.cpp.s
.PHONY : src/engine/components/physics.cpp.s

src/engine/components/render.o: src/engine/components/render.cpp.o
.PHONY : src/engine/components/render.o

# target to build an object file
src/engine/components/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/render.cpp.o
.PHONY : src/engine/components/render.cpp.o

src/engine/components/render.i: src/engine/components/render.cpp.i
.PHONY : src/engine/components/render.i

# target to preprocess a source file
src/engine/components/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/render.cpp.i
.PHONY : src/engine/components/render.cpp.i

src/engine/components/render.s: src/engine/components/render.cpp.s
.PHONY : src/engine/components/render.s

# target to generate assembly for a file
src/engine/components/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/components/render.cpp.s
.PHONY : src/engine/components/render.cpp.s

src/engine/components/server_network.o: src/engine/components/server_network.cpp.o
.PHONY : src/engine/components/server_network.o

# target to build an object file
src/engine/components/server_network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/components/server_network.cpp.o
.PHONY : src/engine/components/server_network.cpp.o

src/engine/components/server_network.i: src/engine/components/server_network.cpp.i
.PHONY : src/engine/components/server_network.i

# target to preprocess a source file
src/engine/components/server_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/components/server_network.cpp.i
.PHONY : src/engine/components/server_network.cpp.i

src/engine/components/server_network.s: src/engine/components/server_network.cpp.s
.PHONY : src/engine/components/server_network.s

# target to generate assembly for a file
src/engine/components/server_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/components/server_network.cpp.s
.PHONY : src/engine/components/server_network.cpp.s

src/engine/mesh_loader.o: src/engine/mesh_loader.cpp.o
.PHONY : src/engine/mesh_loader.o

# target to build an object file
src/engine/mesh_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/mesh_loader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/mesh_loader.cpp.o
.PHONY : src/engine/mesh_loader.cpp.o

src/engine/mesh_loader.i: src/engine/mesh_loader.cpp.i
.PHONY : src/engine/mesh_loader.i

# target to preprocess a source file
src/engine/mesh_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/mesh_loader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/mesh_loader.cpp.i
.PHONY : src/engine/mesh_loader.cpp.i

src/engine/mesh_loader.s: src/engine/mesh_loader.cpp.s
.PHONY : src/engine/mesh_loader.s

# target to generate assembly for a file
src/engine/mesh_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/engine/mesh_loader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/mesh_loader.cpp.s
.PHONY : src/engine/mesh_loader.cpp.s

src/engine/server_engine.o: src/engine/server_engine.cpp.o
.PHONY : src/engine/server_engine.o

# target to build an object file
src/engine/server_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/server_engine.cpp.o
.PHONY : src/engine/server_engine.cpp.o

src/engine/server_engine.i: src/engine/server_engine.cpp.i
.PHONY : src/engine/server_engine.i

# target to preprocess a source file
src/engine/server_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/server_engine.cpp.i
.PHONY : src/engine/server_engine.cpp.i

src/engine/server_engine.s: src/engine/server_engine.cpp.s
.PHONY : src/engine/server_engine.s

# target to generate assembly for a file
src/engine/server_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/engine/server_engine.cpp.s
.PHONY : src/engine/server_engine.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... server"
	@echo "... libs/include/imgui/backends/imgui_impl_glfw.o"
	@echo "... libs/include/imgui/backends/imgui_impl_glfw.i"
	@echo "... libs/include/imgui/backends/imgui_impl_glfw.s"
	@echo "... libs/include/imgui/backends/imgui_impl_opengl3.o"
	@echo "... libs/include/imgui/backends/imgui_impl_opengl3.i"
	@echo "... libs/include/imgui/backends/imgui_impl_opengl3.s"
	@echo "... libs/include/imgui/imgui.o"
	@echo "... libs/include/imgui/imgui.i"
	@echo "... libs/include/imgui/imgui.s"
	@echo "... libs/include/imgui/imgui_draw.o"
	@echo "... libs/include/imgui/imgui_draw.i"
	@echo "... libs/include/imgui/imgui_draw.s"
	@echo "... libs/include/imgui/imgui_tables.o"
	@echo "... libs/include/imgui/imgui_tables.i"
	@echo "... libs/include/imgui/imgui_tables.s"
	@echo "... libs/include/imgui/imgui_widgets.o"
	@echo "... libs/include/imgui/imgui_widgets.i"
	@echo "... libs/include/imgui/imgui_widgets.s"
	@echo "... src/client/game.o"
	@echo "... src/client/game.i"
	@echo "... src/client/game.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/player.o"
	@echo "... src/client/player.i"
	@echo "... src/client/player.s"
	@echo "... src/client/world.o"
	@echo "... src/client/world.i"
	@echo "... src/client/world.s"
	@echo "... src/engine/client_engine.o"
	@echo "... src/engine/client_engine.i"
	@echo "... src/engine/client_engine.s"
	@echo "... src/engine/components/client_network.o"
	@echo "... src/engine/components/client_network.i"
	@echo "... src/engine/components/client_network.s"
	@echo "... src/engine/components/gui.o"
	@echo "... src/engine/components/gui.i"
	@echo "... src/engine/components/gui.s"
	@echo "... src/engine/components/input.o"
	@echo "... src/engine/components/input.i"
	@echo "... src/engine/components/input.s"
	@echo "... src/engine/components/physics.o"
	@echo "... src/engine/components/physics.i"
	@echo "... src/engine/components/physics.s"
	@echo "... src/engine/components/render.o"
	@echo "... src/engine/components/render.i"
	@echo "... src/engine/components/render.s"
	@echo "... src/engine/components/server_network.o"
	@echo "... src/engine/components/server_network.i"
	@echo "... src/engine/components/server_network.s"
	@echo "... src/engine/mesh_loader.o"
	@echo "... src/engine/mesh_loader.i"
	@echo "... src/engine/mesh_loader.s"
	@echo "... src/engine/server_engine.o"
	@echo "... src/engine/server_engine.i"
	@echo "... src/engine/server_engine.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

