# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quinn/Documents/bztest/bz_opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quinn/Documents/bztest/bz_opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Documents/bztest/bz_opengl/CMakeFiles /home/quinn/Documents/bztest/bz_opengl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/Documents/bztest/bz_opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named enet_static

# Build rule for target.
enet_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_static
.PHONY : enet_static

# fast build rule for target.
enet_static/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_static.dir/build.make libs/enet/CMakeFiles/enet_static.dir/build
.PHONY : enet_static/fast

#=============================================================================
# Target rules for targets named enet_test

# Build rule for target.
enet_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_test
.PHONY : enet_test

# fast build rule for target.
enet_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_test.dir/build.make libs/enet/CMakeFiles/enet_test.dir/build
.PHONY : enet_test/fast

#=============================================================================
# Target rules for targets named enet_test_extra_peers

# Build rule for target.
enet_test_extra_peers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_test_extra_peers
.PHONY : enet_test_extra_peers

# fast build rule for target.
enet_test_extra_peers/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_test_extra_peers.dir/build.make libs/enet/CMakeFiles/enet_test_extra_peers.dir/build
.PHONY : enet_test_extra_peers/fast

#=============================================================================
# Target rules for targets named enet_test_unit

# Build rule for target.
enet_test_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enet_test_unit
.PHONY : enet_test_unit

# fast build rule for target.
enet_test_unit/fast:
	$(MAKE) $(MAKESILENT) -f libs/enet/CMakeFiles/enet_test_unit.dir/build.make libs/enet/CMakeFiles/enet_test_unit.dir/build
.PHONY : enet_test_unit/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f libs/spdlog/CMakeFiles/spdlog.dir/build.make libs/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f libs/glm/glm/CMakeFiles/glm.dir/build.make libs/glm/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named threepp

# Build rule for target.
threepp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 threepp
.PHONY : threepp

# fast build rule for target.
threepp/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/src/CMakeFiles/threepp.dir/build.make libs/threepp/src/CMakeFiles/threepp.dir/build
.PHONY : threepp/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/src/external/glfw/src/CMakeFiles/glfw.dir/build.make libs/threepp/src/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/src/external/glfw/src/CMakeFiles/update_mappings.dir/build.make libs/threepp/src/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named PerspectiveCamera_test

# Build rule for target.
PerspectiveCamera_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PerspectiveCamera_test
.PHONY : PerspectiveCamera_test

# fast build rule for target.
PerspectiveCamera_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/cameras/CMakeFiles/PerspectiveCamera_test.dir/build.make libs/threepp/tests/cameras/CMakeFiles/PerspectiveCamera_test.dir/build
.PHONY : PerspectiveCamera_test/fast

#=============================================================================
# Target rules for targets named OrthograpichCamera_test

# Build rule for target.
OrthograpichCamera_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OrthograpichCamera_test
.PHONY : OrthograpichCamera_test

# fast build rule for target.
OrthograpichCamera_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/cameras/CMakeFiles/OrthograpichCamera_test.dir/build.make libs/threepp/tests/cameras/CMakeFiles/OrthograpichCamera_test.dir/build
.PHONY : OrthograpichCamera_test/fast

#=============================================================================
# Target rules for targets named EventDispatcher_test

# Build rule for target.
EventDispatcher_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EventDispatcher_test
.PHONY : EventDispatcher_test

# fast build rule for target.
EventDispatcher_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/core/CMakeFiles/EventDispatcher_test.dir/build.make libs/threepp/tests/core/CMakeFiles/EventDispatcher_test.dir/build
.PHONY : EventDispatcher_test/fast

#=============================================================================
# Target rules for targets named Layers_test

# Build rule for target.
Layers_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Layers_test
.PHONY : Layers_test

# fast build rule for target.
Layers_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/core/CMakeFiles/Layers_test.dir/build.make libs/threepp/tests/core/CMakeFiles/Layers_test.dir/build
.PHONY : Layers_test/fast

#=============================================================================
# Target rules for targets named Object3D_test

# Build rule for target.
Object3D_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Object3D_test
.PHONY : Object3D_test

# fast build rule for target.
Object3D_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/core/CMakeFiles/Object3D_test.dir/build.make libs/threepp/tests/core/CMakeFiles/Object3D_test.dir/build
.PHONY : Object3D_test/fast

#=============================================================================
# Target rules for targets named Raycaster_test

# Build rule for target.
Raycaster_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Raycaster_test
.PHONY : Raycaster_test

# fast build rule for target.
Raycaster_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/core/CMakeFiles/Raycaster_test.dir/build.make libs/threepp/tests/core/CMakeFiles/Raycaster_test.dir/build
.PHONY : Raycaster_test/fast

#=============================================================================
# Target rules for targets named Uniform_test

# Build rule for target.
Uniform_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Uniform_test
.PHONY : Uniform_test

# fast build rule for target.
Uniform_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/core/CMakeFiles/Uniform_test.dir/build.make libs/threepp/tests/core/CMakeFiles/Uniform_test.dir/build
.PHONY : Uniform_test/fast

#=============================================================================
# Target rules for targets named Box2_test

# Build rule for target.
Box2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Box2_test
.PHONY : Box2_test

# fast build rule for target.
Box2_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Box2_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Box2_test.dir/build
.PHONY : Box2_test/fast

#=============================================================================
# Target rules for targets named Box3_test

# Build rule for target.
Box3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Box3_test
.PHONY : Box3_test

# fast build rule for target.
Box3_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Box3_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Box3_test.dir/build
.PHONY : Box3_test/fast

#=============================================================================
# Target rules for targets named Color_test

# Build rule for target.
Color_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Color_test
.PHONY : Color_test

# fast build rule for target.
Color_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Color_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Color_test.dir/build
.PHONY : Color_test/fast

#=============================================================================
# Target rules for targets named Cylindrical_test

# Build rule for target.
Cylindrical_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cylindrical_test
.PHONY : Cylindrical_test

# fast build rule for target.
Cylindrical_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Cylindrical_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Cylindrical_test.dir/build
.PHONY : Cylindrical_test/fast

#=============================================================================
# Target rules for targets named Euler_test

# Build rule for target.
Euler_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Euler_test
.PHONY : Euler_test

# fast build rule for target.
Euler_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Euler_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Euler_test.dir/build
.PHONY : Euler_test/fast

#=============================================================================
# Target rules for targets named Frustum_test

# Build rule for target.
Frustum_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Frustum_test
.PHONY : Frustum_test

# fast build rule for target.
Frustum_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Frustum_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Frustum_test.dir/build
.PHONY : Frustum_test/fast

#=============================================================================
# Target rules for targets named MathUtils_test

# Build rule for target.
MathUtils_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MathUtils_test
.PHONY : MathUtils_test

# fast build rule for target.
MathUtils_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/MathUtils_test.dir/build.make libs/threepp/tests/math/CMakeFiles/MathUtils_test.dir/build
.PHONY : MathUtils_test/fast

#=============================================================================
# Target rules for targets named Sphere_test

# Build rule for target.
Sphere_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sphere_test
.PHONY : Sphere_test

# fast build rule for target.
Sphere_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Sphere_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Sphere_test.dir/build
.PHONY : Sphere_test/fast

#=============================================================================
# Target rules for targets named Spherical_test

# Build rule for target.
Spherical_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Spherical_test
.PHONY : Spherical_test

# fast build rule for target.
Spherical_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Spherical_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Spherical_test.dir/build
.PHONY : Spherical_test/fast

#=============================================================================
# Target rules for targets named Triangle_test

# Build rule for target.
Triangle_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Triangle_test
.PHONY : Triangle_test

# fast build rule for target.
Triangle_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Triangle_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Triangle_test.dir/build
.PHONY : Triangle_test/fast

#=============================================================================
# Target rules for targets named Ray_test

# Build rule for target.
Ray_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ray_test
.PHONY : Ray_test

# fast build rule for target.
Ray_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Ray_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Ray_test.dir/build
.PHONY : Ray_test/fast

#=============================================================================
# Target rules for targets named Vector2_test

# Build rule for target.
Vector2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vector2_test
.PHONY : Vector2_test

# fast build rule for target.
Vector2_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Vector2_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Vector2_test.dir/build
.PHONY : Vector2_test/fast

#=============================================================================
# Target rules for targets named Vector3_test

# Build rule for target.
Vector3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vector3_test
.PHONY : Vector3_test

# fast build rule for target.
Vector3_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Vector3_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Vector3_test.dir/build
.PHONY : Vector3_test/fast

#=============================================================================
# Target rules for targets named Vector4_test

# Build rule for target.
Vector4_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vector4_test
.PHONY : Vector4_test

# fast build rule for target.
Vector4_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Vector4_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Vector4_test.dir/build
.PHONY : Vector4_test/fast

#=============================================================================
# Target rules for targets named Matrix4_test

# Build rule for target.
Matrix4_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Matrix4_test
.PHONY : Matrix4_test

# fast build rule for target.
Matrix4_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Matrix4_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Matrix4_test.dir/build
.PHONY : Matrix4_test/fast

#=============================================================================
# Target rules for targets named Quaternion_test

# Build rule for target.
Quaternion_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Quaternion_test
.PHONY : Quaternion_test

# fast build rule for target.
Quaternion_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/math/CMakeFiles/Quaternion_test.dir/build.make libs/threepp/tests/math/CMakeFiles/Quaternion_test.dir/build
.PHONY : Quaternion_test/fast

#=============================================================================
# Target rules for targets named StringUtils_test

# Build rule for target.
StringUtils_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StringUtils_test
.PHONY : StringUtils_test

# fast build rule for target.
StringUtils_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/utils/CMakeFiles/StringUtils_test.dir/build.make libs/threepp/tests/utils/CMakeFiles/StringUtils_test.dir/build
.PHONY : StringUtils_test/fast

#=============================================================================
# Target rules for targets named TaskManager_test

# Build rule for target.
TaskManager_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TaskManager_test
.PHONY : TaskManager_test

# fast build rule for target.
TaskManager_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/utils/CMakeFiles/TaskManager_test.dir/build.make libs/threepp/tests/utils/CMakeFiles/TaskManager_test.dir/build
.PHONY : TaskManager_test/fast

#=============================================================================
# Target rules for targets named GLRenderLists_test

# Build rule for target.
GLRenderLists_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GLRenderLists_test
.PHONY : GLRenderLists_test

# fast build rule for target.
GLRenderLists_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/renderers/gl/CMakeFiles/GLRenderLists_test.dir/build.make libs/threepp/tests/renderers/gl/CMakeFiles/GLRenderLists_test.dir/build
.PHONY : GLRenderLists_test/fast

#=============================================================================
# Target rules for targets named Fontloader_test

# Build rule for target.
Fontloader_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fontloader_test
.PHONY : Fontloader_test

# fast build rule for target.
Fontloader_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/loaders/CMakeFiles/Fontloader_test.dir/build.make libs/threepp/tests/loaders/CMakeFiles/Fontloader_test.dir/build
.PHONY : Fontloader_test/fast

#=============================================================================
# Target rules for targets named SVGFunctions_test

# Build rule for target.
SVGFunctions_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SVGFunctions_test
.PHONY : SVGFunctions_test

# fast build rule for target.
SVGFunctions_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/threepp/tests/loaders/svg/CMakeFiles/SVGFunctions_test.dir/build.make libs/threepp/tests/loaders/svg/CMakeFiles/SVGFunctions_test.dir/build
.PHONY : SVGFunctions_test/fast

src/client/client.o: src/client/client.cpp.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/client/input.o: src/client/input.cpp.o
.PHONY : src/client/input.o

# target to build an object file
src/client/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/input.cpp.o
.PHONY : src/client/input.cpp.o

src/client/input.i: src/client/input.cpp.i
.PHONY : src/client/input.i

# target to preprocess a source file
src/client/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/input.cpp.i
.PHONY : src/client/input.cpp.i

src/client/input.s: src/client/input.cpp.s
.PHONY : src/client/input.s

# target to generate assembly for a file
src/client/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/input.cpp.s
.PHONY : src/client/input.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/networker.o: src/client/networker.cpp.o
.PHONY : src/client/networker.o

# target to build an object file
src/client/networker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/networker.cpp.o
.PHONY : src/client/networker.cpp.o

src/client/networker.i: src/client/networker.cpp.i
.PHONY : src/client/networker.i

# target to preprocess a source file
src/client/networker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/networker.cpp.i
.PHONY : src/client/networker.cpp.i

src/client/networker.s: src/client/networker.cpp.s
.PHONY : src/client/networker.s

# target to generate assembly for a file
src/client/networker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/networker.cpp.s
.PHONY : src/client/networker.cpp.s

src/client/player.o: src/client/player.cpp.o
.PHONY : src/client/player.o

# target to build an object file
src/client/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.o
.PHONY : src/client/player.cpp.o

src/client/player.i: src/client/player.cpp.i
.PHONY : src/client/player.i

# target to preprocess a source file
src/client/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.i
.PHONY : src/client/player.cpp.i

src/client/player.s: src/client/player.cpp.s
.PHONY : src/client/player.s

# target to generate assembly for a file
src/client/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/player.cpp.s
.PHONY : src/client/player.cpp.s

src/client/renderer.o: src/client/renderer.cpp.o
.PHONY : src/client/renderer.o

# target to build an object file
src/client/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/renderer.cpp.o
.PHONY : src/client/renderer.cpp.o

src/client/renderer.i: src/client/renderer.cpp.i
.PHONY : src/client/renderer.i

# target to preprocess a source file
src/client/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/renderer.cpp.i
.PHONY : src/client/renderer.cpp.i

src/client/renderer.s: src/client/renderer.cpp.s
.PHONY : src/client/renderer.s

# target to generate assembly for a file
src/client/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/renderer.cpp.s
.PHONY : src/client/renderer.cpp.s

src/client/shot.o: src/client/shot.cpp.o
.PHONY : src/client/shot.o

# target to build an object file
src/client/shot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/shot.cpp.o
.PHONY : src/client/shot.cpp.o

src/client/shot.i: src/client/shot.cpp.i
.PHONY : src/client/shot.i

# target to preprocess a source file
src/client/shot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/shot.cpp.i
.PHONY : src/client/shot.cpp.i

src/client/shot.s: src/client/shot.cpp.s
.PHONY : src/client/shot.s

# target to generate assembly for a file
src/client/shot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/shot.cpp.s
.PHONY : src/client/shot.cpp.s

src/server/client.o: src/server/client.cpp.o
.PHONY : src/server/client.o

# target to build an object file
src/server/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client.cpp.o
.PHONY : src/server/client.cpp.o

src/server/client.i: src/server/client.cpp.i
.PHONY : src/server/client.i

# target to preprocess a source file
src/server/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client.cpp.i
.PHONY : src/server/client.cpp.i

src/server/client.s: src/server/client.cpp.s
.PHONY : src/server/client.s

# target to generate assembly for a file
src/server/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/client.cpp.s
.PHONY : src/server/client.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/server/networker.o: src/server/networker.cpp.o
.PHONY : src/server/networker.o

# target to build an object file
src/server/networker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/networker.cpp.o
.PHONY : src/server/networker.cpp.o

src/server/networker.i: src/server/networker.cpp.i
.PHONY : src/server/networker.i

# target to preprocess a source file
src/server/networker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/networker.cpp.i
.PHONY : src/server/networker.cpp.i

src/server/networker.s: src/server/networker.cpp.s
.PHONY : src/server/networker.s

# target to generate assembly for a file
src/server/networker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/networker.cpp.s
.PHONY : src/server/networker.cpp.s

src/server/shot.o: src/server/shot.cpp.o
.PHONY : src/server/shot.o

# target to build an object file
src/server/shot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/shot.cpp.o
.PHONY : src/server/shot.cpp.o

src/server/shot.i: src/server/shot.cpp.i
.PHONY : src/server/shot.i

# target to preprocess a source file
src/server/shot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/shot.cpp.i
.PHONY : src/server/shot.cpp.i

src/server/shot.s: src/server/shot.cpp.s
.PHONY : src/server/shot.s

# target to generate assembly for a file
src/server/shot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/shot.cpp.s
.PHONY : src/server/shot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... Box2_test"
	@echo "... Box3_test"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... Color_test"
	@echo "... Cylindrical_test"
	@echo "... Euler_test"
	@echo "... EventDispatcher_test"
	@echo "... Fontloader_test"
	@echo "... Frustum_test"
	@echo "... GLRenderLists_test"
	@echo "... Layers_test"
	@echo "... MathUtils_test"
	@echo "... Matrix4_test"
	@echo "... Object3D_test"
	@echo "... OrthograpichCamera_test"
	@echo "... PerspectiveCamera_test"
	@echo "... Quaternion_test"
	@echo "... Ray_test"
	@echo "... Raycaster_test"
	@echo "... SVGFunctions_test"
	@echo "... Sphere_test"
	@echo "... Spherical_test"
	@echo "... StringUtils_test"
	@echo "... TaskManager_test"
	@echo "... Triangle_test"
	@echo "... Uniform_test"
	@echo "... Vector2_test"
	@echo "... Vector3_test"
	@echo "... Vector4_test"
	@echo "... client"
	@echo "... enet_static"
	@echo "... enet_test"
	@echo "... enet_test_extra_peers"
	@echo "... enet_test_unit"
	@echo "... glfw"
	@echo "... glm"
	@echo "... server"
	@echo "... spdlog"
	@echo "... threepp"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/client/input.o"
	@echo "... src/client/input.i"
	@echo "... src/client/input.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/networker.o"
	@echo "... src/client/networker.i"
	@echo "... src/client/networker.s"
	@echo "... src/client/player.o"
	@echo "... src/client/player.i"
	@echo "... src/client/player.s"
	@echo "... src/client/renderer.o"
	@echo "... src/client/renderer.i"
	@echo "... src/client/renderer.s"
	@echo "... src/client/shot.o"
	@echo "... src/client/shot.i"
	@echo "... src/client/shot.s"
	@echo "... src/server/client.o"
	@echo "... src/server/client.i"
	@echo "... src/server/client.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/networker.o"
	@echo "... src/server/networker.i"
	@echo "... src/server/networker.s"
	@echo "... src/server/shot.o"
	@echo "... src/server/shot.i"
	@echo "... src/server/shot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

